Fix AuthError -  Error: Amplify has not been configured correctly.
index.js:1 [ERROR] 59:57.656 AuthError -
            Error: Amplify has not been configured correctly.
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:

            1. Did you run `amplify push` after adding auth via `amplify add auth`?
                See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

            2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.

Fix: https://github.com/aws-amplify/amplify-js/discussions/5836#discussioncomment-47721